version: '3'

services:
  blog-mysql:
    image: blogmysql:0.1
    ports:
      - 3306:3306
    volumes:
      - mysql-data:/var/lib/mysql

  blog-redis:
    image: redis
    ports:
      - 6379:6379
    command: redis-server --save 60 1 --loglevel warning
    volumes:
      - redis-data:/data

volumes:
  mysql-data:
    driver: local

  redis-data:
    driver: local